name: LookAway
options:
  bundleIdPrefix: com.yourapp
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"

packages:
  LookAwayCore:
    path: Packages/LookAwayCore

targets:
  LookAway-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: LookAway-macOS
    dependencies:
      - package: LookAwayCore
    info:
      path: LookAway-macOS/Info.plist
      properties:
        LSUIElement: true           # menu bar agent, no Dock icon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourapp.lookaway.macos
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        PRODUCT_NAME: LookAway
    entitlements:
      path: LookAway-macOS/LookAway-macOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.yourapp.lookaway
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.yourapp.lookaway
        com.apple.developer.aps-environment: development

  LookAway-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LookAway-iOS
    dependencies:
      - package: LookAwayCore
    info:
      path: LookAway-iOS/Info.plist
      properties:
        UIBackgroundModes:
          - fetch
          - remote-notification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourapp.lookaway.ios
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        PRODUCT_NAME: LookAway
    entitlements:
      path: LookAway-iOS/LookAway-iOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.yourapp.lookaway
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.yourapp.lookaway
        com.apple.developer.aps-environment: development
