name: LockOut
options:
  bundleIdPrefix: com.yourapp
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"

packages:
  LockOutCore:
    path: Packages/LockOutCore

targets:
  LockOut-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: LockOut-macOS
    dependencies:
      - package: LockOutCore
    info:
      path: LockOut-macOS/Info.plist
      properties:
        LSUIElement: true           # menu bar agent, no Dock icon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourapp.lockout.macos
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        PRODUCT_NAME: LockOut
    entitlements:
      path: LockOut-macOS/LockOut-macOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.yourapp.lockout
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.yourapp.lockout
        com.apple.developer.aps-environment: development

  LockOut-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LockOut-iOS
    dependencies:
      - package: LockOutCore
    info:
      path: LockOut-iOS/Info.plist
      properties:
        UIBackgroundModes:
          - fetch
          - remote-notification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourapp.lockout.ios
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        PRODUCT_NAME: LockOut
    entitlements:
      path: LockOut-iOS/LockOut-iOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.yourapp.lockout
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.yourapp.lockout
        com.apple.developer.aps-environment: development
