name: LookAway
options:
  bundleIdPrefix: com.yourapp
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"

packages:
  LookAwayCore:
    path: Packages/LookAwayCore

targets:
  LookAway-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: LookAway-macOS
    dependencies:
      - package: LookAwayCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourapp.lookaway.macos
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        PRODUCT_NAME: LookAway
    entitlements:
      path: LookAway-macOS/LookAway-macOS.entitlements

  LookAway-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LookAway-iOS
    dependencies:
      - package: LookAwayCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourapp.lookaway.ios
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_NAME: LookAway
    entitlements:
      path: LookAway-iOS/LookAway-iOS.entitlements
