name: LockOut
options:
  bundleIdPrefix: com.yourapp
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"

packages:
  LockOutCore:
    path: Packages/LockOutCore
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"

targets:
  LockOut-macOS:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: LockOut-macOS
    dependencies:
      - package: LockOutCore
      - package: Sparkle
        product: Sparkle
    info:
      path: LockOut-macOS/Info.plist
      properties:
        LSUIElement: true           # menu bar agent, no Dock icon
        SUFeedURL: "$(SPARKLE_FEED_URL)"
        SUPublicEDKey: "$(SPARKLE_ED_KEY)"
        CLOUDKIT_CONTAINER_ID: "$(CLOUDKIT_CONTAINER_ID)"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        PRODUCT_NAME: LockOut
        CODE_SIGN_IDENTITY: "Developer ID Application"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
      xcconfigs:
        base: Config.xcconfig
    entitlements:
      path: LockOut-macOS/LockOut-macOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.yourapp.lockout
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.yourapp.lockout
        com.apple.security.hardened-runtime: true
        com.apple.security.cs.allow-unsigned-executable-memory: false
        com.apple.security.cs.disable-library-validation: false

schemes:
  LockOut-macOS:
    build:
      targets:
        LockOut-macOS: all
    run:
      config: Debug
    archive:
      config: Release
